def patch(path, old, new, label):
    try:
        with open(path, "r", encoding="utf-8") as f:
            content = f.read()
    except FileNotFoundError:
        print(f"WARNING [{label}]: file not found: {path} — SKIPPED")
        return
    if new in content:
        print(f"OK [{label}]: already applied earlier, skipping — {path}")
        return
    if old not in content:
        print(f"WARNING [{label}]: anchor text not found in {path} — SKIPPED (file may have changed, needs manual check)")
        return
    if content.count(old) > 1:
        print(f"WARNING [{label}]: anchor text found MORE THAN ONCE in {path} — SKIPPED (ambiguous, needs manual check)")
        return
    content = content.replace(old, new)
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)
    print(f"OK [{label}]: patched {path}")


patch(
    'frontend/src/pages/PromoterLogin.jsx',
    '          <img src={LOGO_URL} alt="BatchMock.in" className="w-12 h-12 mx-auto object-contain rounded-xl mb-4" />',
    '          <img src={LOGO_URL} alt="AntimPrayash.in" className="w-12 h-12 mx-auto object-contain rounded-xl mb-4" />',
    'PromoterLogin.jsx:52',
)

patch(
    'frontend/src/pages/Singup.jsx',
    '        <img src="/logo.svg" alt="BatchMock.in" className="w-14 h-14 object-contain mb-6" />',
    '        <img src="/logo.svg" alt="AntimPrayash.in" className="w-14 h-14 object-contain mb-6" />',
    'Singup.jsx:194',
)

patch(
    'frontend/src/pages/Singup.jsx',
    '        <h1 className="text-3xl font-bold mb-3">BatchMock.in mein Swagat Hai</h1>',
    '        <h1 className="text-3xl font-bold mb-3">AntimPrayash.in mein Swagat Hai</h1>',
    'Singup.jsx:195',
)

patch(
    'frontend/src/pages/PrivacyPolicy.jsx',
    '            BatchMock.in ("we", "our", "the platform") provides mock tests, previous year papers, and',
    '            AntimPrayash.in ("we", "our", "the platform") provides mock tests, previous year papers, and',
    'PrivacyPolicy.jsx:26',
)

patch(
    'frontend/src/pages/UserTopicAnalysis.jsx',
    '          <img src={LOGO_URL} alt="BatchMock.in" className="w-7 h-7 sm:w-8 sm:h-8 object-contain rounded" />',
    '          <img src={LOGO_URL} alt="AntimPrayash.in" className="w-7 h-7 sm:w-8 sm:h-8 object-contain rounded" />',
    'UserTopicAnalysis.jsx:233',
)

patch(
    'frontend/src/pages/UserTopicAnalysis.jsx',
    '          <span className="text-sm sm:text-xl font-semibold tracking-wide">BatchMock.in</span>',
    '          <span className="text-sm sm:text-xl font-semibold tracking-wide">AntimPrayash.in</span>',
    'UserTopicAnalysis.jsx:234',
)

patch(
    'frontend/src/pages/UserSubjectAnallysis.jsx',
    '          <img src={LOGO_URL} alt="BatchMock.in" className="w-8 h-8 object-contain rounded flex-shrink-0" />',
    '          <img src={LOGO_URL} alt="AntimPrayash.in" className="w-8 h-8 object-contain rounded flex-shrink-0" />',
    'UserSubjectAnallysis.jsx:212',
)

patch(
    'frontend/src/pages/UserSubjectAnallysis.jsx',
    '          <span className="text-base sm:text-xl font-semibold tracking-wide">BatchMock.in</span>',
    '          <span className="text-base sm:text-xl font-semibold tracking-wide">AntimPrayash.in</span>',
    'UserSubjectAnallysis.jsx:213',
)

patch(
    'frontend/src/pages/AdminLogin.jsx',
    '          <img src={LOGO_URL} alt="BatchMock.in" className="w-12 h-12 mx-auto object-contain rounded-xl mb-4" />',
    '          <img src={LOGO_URL} alt="AntimPrayash.in" className="w-12 h-12 mx-auto object-contain rounded-xl mb-4" />',
    'AdminLogin.jsx:35',
)

patch(
    'frontend/src/pages/UserAllAnalysis.jsx',
    '          <img src={LOGO_URL} alt="BatchMock.in" className="w-8 h-8 object-contain rounded flex-shrink-0" />',
    '          <img src={LOGO_URL} alt="AntimPrayash.in" className="w-8 h-8 object-contain rounded flex-shrink-0" />',
    'UserAllAnalysis.jsx:428',
)

patch(
    'frontend/src/pages/UserAllAnalysis.jsx',
    '          <span className="text-base sm:text-xl font-semibold tracking-wide">BatchMock.in</span>',
    '          <span className="text-base sm:text-xl font-semibold tracking-wide">AntimPrayash.in</span>',
    'UserAllAnalysis.jsx:429',
)

patch(
    'frontend/src/pages/teacher/TeacherStudentReportPrint.jsx',
    '        <p className="text-[11px] text-gray-400 mt-10 pt-4 border-t border-gray-200">Generated by BatchMock.in</p>',
    '        <p className="text-[11px] text-gray-400 mt-10 pt-4 border-t border-gray-200">Generated by AntimPrayash.in</p>',
    'TeacherStudentReportPrint.jsx:180',
)

patch(
    'frontend/src/pages/teacher/TeacherLogin.jsx',
    '          <img src={LOGO_URL} alt="BatchMock.in" className="w-12 h-12 mx-auto object-contain rounded-xl mb-4" />',
    '          <img src={LOGO_URL} alt="AntimPrayash.in" className="w-12 h-12 mx-auto object-contain rounded-xl mb-4" />',
    'TeacherLogin.jsx:49',
)

patch(
    'frontend/src/pages/teacher/TeacherForgotPassword.jsx',
    '          <img src={LOGO_URL} alt="BatchMock.in" className="w-12 h-12 mx-auto object-contain rounded-xl mb-4" />',
    '          <img src={LOGO_URL} alt="AntimPrayash.in" className="w-12 h-12 mx-auto object-contain rounded-xl mb-4" />',
    'TeacherForgotPassword.jsx:125',
)

patch(
    'frontend/src/pages/Landing.jsx',
    '          <img src={LOGO_URL} alt="BatchMock.in" className="w-8 h-8 object-contain rounded" />',
    '          <img src={LOGO_URL} alt="AntimPrayash.in" className="w-8 h-8 object-contain rounded" />',
    'Landing.jsx:39',
)

patch(
    'frontend/src/pages/Landing.jsx',
    '          <span className="text-base sm:text-xl font-semibold tracking-wide">BatchMock.in</span>',
    '          <span className="text-base sm:text-xl font-semibold tracking-wide">AntimPrayash.in</span>',
    'Landing.jsx:40',
)

patch(
    'frontend/src/pages/Landing.jsx',
    '          <p className="text-xs text-gray-500">© {new Date().getFullYear()} BatchMock.in — All rights reserved</p>',
    '          <p className="text-xs text-gray-500">© {new Date().getFullYear()} AntimPrayash.in — All rights reserved</p>',
    'Landing.jsx:106',
)

patch(
    'frontend/src/pages/HomePage.jsx',
    '        <img src={LOGO_URL} alt="BatchMock.in" className="w-8 h-8 object-contain rounded-lg" />',
    '        <img src={LOGO_URL} alt="AntimPrayash.in" className="w-8 h-8 object-contain rounded-lg" />',
    'HomePage.jsx:232',
)

patch(
    'frontend/src/pages/HomePage.jsx',
    '        <span className="ml-2.5 text-base font-bold tracking-tight">BatchMock.in</span>',
    '        <span className="ml-2.5 text-base font-bold tracking-tight">AntimPrayash.in</span>',
    'HomePage.jsx:233',
)

patch(
    'frontend/src/pages/Login.jsx',
    '          <img src="/logo.svg" alt="BatchMock.in" className="w-7 h-7 object-contain"/>',
    '          <img src="/logo.svg" alt="AntimPrayash.in" className="w-7 h-7 object-contain"/>',
    'Login.jsx:115',
)

patch(
    'frontend/src/pages/Login.jsx',
    '          <span className="text-xl font-bold tracking-tight text-[#0F172A]">BatchMock.in</span>',
    '          <span className="text-xl font-bold tracking-tight text-[#0F172A]">AntimPrayash.in</span>',
    'Login.jsx:116',
)

patch(
    'frontend/src/pages/Login.jsx',
    '          <p className="text-lg text-[#64748B] mb-8 font-normal px-4">Continue your preparation and track your success journey with BatchMock.in.</p>',
    '          <p className="text-lg text-[#64748B] mb-8 font-normal px-4">Continue your preparation and track your success journey with AntimPrayash.in.</p>',
    'Login.jsx:121',
)

patch(
    'frontend/src/pages/Login.jsx',
    '            <img src="/logo.svg" alt="BatchMock.in" className="w-8 h-8 object-contain"/>',
    '            <img src="/logo.svg" alt="AntimPrayash.in" className="w-8 h-8 object-contain"/>',
    'Login.jsx:168',
)

patch(
    'frontend/src/pages/Login.jsx',
    '            <span className="text-2xl font-bold tracking-tight text-[#0F172A]">BatchMock.in</span>',
    '            <span className="text-2xl font-bold tracking-tight text-[#0F172A]">AntimPrayash.in</span>',
    'Login.jsx:169',
)

patch(
    'backend/controllers/bulkManageStudents.js',
    '            email: `${phone}@student.batchmock.in`,',
    '            email: `${phone}@student.antimprayash.in`,',
    'bulkManageStudents.js:132',
)

patch(
    'backend/controllers/inviteSubTeacher.js',
    '        email: `pending_${cleanPhone}@invite.batchmock.in`, // 🆕 rebrand',
    '        email: `pending_${cleanPhone}@invite.antimprayash.in`, // 🆕 rebrand',
    'inviteSubTeacher.js:137',
)

patch(
    'backend/utils/mailer.js',
    '  const senderName = process.env.BREVO_SENDER_NAME || "BatchMock.in";',
    '  const senderName = process.env.BREVO_SENDER_NAME || "AntimPrayash.in";',
    'mailer.js:45',
)

patch(
    'backend/utils/mailer.js',
    '    <div style="font-weight: 700; font-size: 18px; margin-bottom: 20px;">BatchMock.in</div>',
    '    <div style="font-weight: 700; font-size: 18px; margin-bottom: 20px;">AntimPrayash.in</div>',
    'mailer.js:89',
)

patch(
    'backend/utils/mailer.js',
    '    subject: `${otpCode} — aapka BatchMock.in OTP`,',
    '    subject: `${otpCode} — aapka AntimPrayash.in OTP`,',
    'mailer.js:101',
)

patch(
    'backend/utils/mailer.js',
    '    text: `Aapka BatchMock.in OTP: ${otpCode} (5 minute mein expire hoga)`,',
    '    text: `Aapka AntimPrayash.in OTP: ${otpCode} (5 minute mein expire hoga)`,',
    'mailer.js:108',
)

patch(
    'backend/utils/mailer.js',
    '    subject: "BatchMock.in Admin Login Link",',
    '    subject: "AntimPrayash.in Admin Login Link",',
    'mailer.js:115',
)

patch(
    'backend/utils/mailer.js',
    '    subject: `BatchMock.in par ${roleText} ke roop mein invite`,',
    '    subject: `AntimPrayash.in par ${roleText} ke roop mein invite`,',
    'mailer.js:130',
)

patch(
    'backend/utils/mailer.js',
    '    subject: "BatchMock.in par Promoter account ban gaya hai",',
    '    subject: "AntimPrayash.in par Promoter account ban gaya hai",',
    'mailer.js:144',
)

patch(
    'frontend/public/manifest.json',
    '  "name": "BatchMock.in",',
    '  "name": "AntimPrayash.in",',
    'manifest.json:2',
)

patch(
    'frontend/public/manifest.json',
    '  "short_name": "BatchMock",',
    '  "short_name": "AntimPrayash",',
    'manifest.json:3',
)

patch(
    'frontend/index.html',
    '    <title>BatchMock.in</title>',
    '    <title>AntimPrayash.in</title>',
    'index.html:10',
)

patch(
    'backend/utils/mailer.js',
    '//        BREVO_SENDER_NAME=BatchMock.in',
    '//        BREVO_SENDER_NAME=AntimPrayash.in',
    'mailer.js:23 (env var example comment)',
)

print("")
print("Done. Read every OK/WARNING line above.")